version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    expose:
      - "5000"

  nginx:
    image: nginx:1.22
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl/certs:ro
      - ./private:/etc/ssl/private:ro
    ports:
      - "${NGINX_PORT}:8443"
    depends_on:
      - flask
